apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: downstream-nodejs-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: downstream-nodejs
status:
  loadBalancer: {}
