apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: downstream-nodejs
  name: downstream-nodejs
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: downstream-nodejs
  type: ClusterIP
status:
  loadBalancer: {}
