apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: downstream-nodejs
  name: downstream-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downstream-nodejs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: downstream-nodejs
    spec:
      containers:
      - image: heroku/nodejs-hello-world
        name: nodejs-hello-world
        ports:
        - containerPort: 3000
        resources: {}
status: {}
