apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: upstream-nginx
  name: upstream-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upstream-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: upstream-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - 'curl http://downstream-nodejs:3000'
status: {}
