apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: downstream-httpd-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: downstream-httpd
status:
  loadBalancer: {}
